# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_block',
            name='id',
        ),
        migrations.AlterField(
            model_name='hostel_block',
            name='block_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
