# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20161016_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_no', models.IntegerField(primary_key=True, serialize=False)),
                ('c_category', models.CharField(max_length=20)),
                ('c_description', models.TextField()),
                ('c_status', models.CharField(choices=[('Recieved', 'Recieved'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_office',
            fields=[
                ('dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_date', models.DateField()),
                ('w_cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Complaint')),
                ('w_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='c_deptno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Hostel_office'),
        ),
    ]
