# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_no', models.IntegerField()),
                ('room_type', models.CharField(choices=[('SSR', 'single shared room'), ('DSR', 'double shared room'), ('TSR', 'triple shared room'), ('D', 'dormitory')], max_length=20)),
                ('room_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(choices=[('GH', 'girls hostel top mess'), ('IH', 'girls hostel down mess'), ('MM', 'Mega mess'), ('FB', 'First Block mess'), ('SB', 'Second Block mess'), ('TB', 'Third Block mess')], max_length=25)),
                ('per_day_cost', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('morning', models.TextField()),
                ('afternoon', models.TextField()),
                ('snacks', models.TextField()),
                ('dinner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('validity', models.DateField()),
                ('block_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Hostel_block')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sem', models.IntegerField()),
                ('dob', models.DateField()),
                ('roll_no', models.CharField(max_length=6, unique=True)),
                ('reg_no', models.CharField(max_length=6, unique=True)),
                ('hostel_feeno', models.CharField(max_length=6, unique=True)),
                ('coll_feeno', models.CharField(max_length=6, unique=True)),
                ('mess_no', models.IntegerField()),
                ('branch', models.CharField(max_length=25)),
                ('mess_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Mess')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Room')),
            ],
        ),
    ]
