# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20161016_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='mess',
            name='mess_name',
            field=models.CharField(choices=[('GH', 'girls hostel top mess'), ('IH', 'girls hostel down mess'), ('MM', 'Mega mess'), ('FB', 'First Block mess'), ('SB', 'Second Block mess'), ('TB', 'Third Block mess')], max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
