# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20161101_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coll_feeno',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mess_no',
            field=models.IntegerField(blank=True),
        ),
    ]
