# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20161104_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='writes',
            name='w_cno',
        ),
        migrations.RemoveField(
            model_name='writes',
            name='w_rollno',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='c_no',
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='day',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Writes',
        ),
        migrations.AddField(
            model_name='complaint_register',
            name='cr_cno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Complaint'),
        ),
        migrations.AddField(
            model_name='complaint_register',
            name='cr_rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student'),
        ),
    ]
