# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_remove_complaint_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='c_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 6, 57, 18, 762164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 6, 57, 18, 759566, tzinfo=utc)),
        ),
    ]
